### ISSUE TITLE
How are you loading the entrant classes?

### ISSUE THREAD

**Issue by AJMansfield** [CommonGuy/AlienWar#1]
I was looking at the source code, but I can't seem to find where you are loading the classes for the entries. Where is that?

**Comment by michaelblyons** [comment]
@AJMansfield I don't know if you're still having trouble, but look at [Planet.java](https://github.com/CommonGuy/AlienWar/blob/master/src/planet/Planet.java#L16) line 16.

**Comment by AJMansfield** [comment]
@michaelblyons Ok, thanks. Just wondering if it was just that, or if you had a class loading mechanism hidden somewhere else.
